package main

import (
	"errors"
	"log"
	"net"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

// validLanACLIPorCIDR reports whether v is a well-formed IP (v4 or v6) or CIDR
// usable inside the nftables set element lists generated by
// applyNftablesConfig. Unlike isValidIPOrCIDR (which is scoped to OSPF static
// routes and deliberately rejects IPv6 and private supernets), this accepts the
// LAN ranges and protocols the nft template actually supports (ip/ip6, /32,
// /64, private supernets like 192.168.0.0/16).
func validLanACLIPorCIDR(v string) bool {
	if strings.Contains(v, "/") {
		_, ipNet, err := net.ParseCIDR(v)
		if err != nil {
			return false
		}
		ones, bits := ipNet.Mask.Size()
		return ones > 0 && bits > 0 && ones <= bits
	}
	ip := net.ParseIP(v)
	return ip != nil
}

type LanACLController struct {
	repo *LanACLRepository
}

func NewLanACLController(repo *LanACLRepository) *LanACLController {
	return &LanACLController{repo: repo}
}

func (ctl *LanACLController) List(c *gin.Context) {
	window, ok := parsePageWindow(c)
	if !ok {
		return
	}
	recs, err := ctl.repo.List()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "db query error"})
		return
	}
	recs = pageSlice(c, window, recs)
	acls := make([]map[string]interface{}, 0, len(recs))
	for _, rec := range recs {
		acls = append(acls, map[string]interface{}{
			"id":         rec.ID,
			"type":       rec.Type,
			"value":      rec.Value,
			"policy":     rec.Policy,
			"remark":     rec.Remark,
			"created_at": rec.CreatedAt,
		})
	}
	c.JSON(http.StatusOK, gin.H{"acls": acls, "default_policy": ctl.repo.GetDefaultPolicy()})
}

func (ctl *LanACLController) Create(c *gin.Context) {
	var req struct {
		Type   string `json:"type"`
		Value  string `json:"value"`
		Policy string `json:"policy"`
		Remark string `json:"remark"`
	}
	if err := c.BindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "bad request"})
		return
	}

	// The value is interpolated verbatim into the nftables set template
	// (applyNftablesConfig), so it must be a well-formed MAC or IP/CIDR — an
	// arbitrary string could corrupt or inject into the generated ruleset.
	req.Type = strings.ToLower(strings.TrimSpace(req.Type))
	req.Policy = strings.ToLower(strings.TrimSpace(req.Policy))
	req.Value = strings.TrimSpace(req.Value)
	if req.Type != "mac" && req.Type != "ip" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid type (mac|ip)"})
		return
	}
	if req.Policy != "proxy" && req.Policy != "direct" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid policy (proxy|direct)"})
		return
	}
	if req.Type == "mac" {
		if _, err := net.ParseMAC(req.Value); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid MAC address"})
			return
		}
	} else if !validLanACLIPorCIDR(req.Value) {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid IP/CIDR"})
		return
	}

	newID, err := ctl.repo.CreateReturningID(req.Type, req.Value, req.Policy, req.Remark)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to add acl"})
		return
	}
	if err := applyNftablesConfigFn(); err != nil {
		// The ruleset still reflects the old list; leaving the row would show
		// an ACL in the UI that the firewall does not enforce.
		if rbErr := ctl.repo.DeleteByID(newID); rbErr != nil {
			log.Printf("[WARN] rollback of lan_acl %d after failed apply: %v", newID, rbErr)
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to apply nftables: " + err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

func (ctl *LanACLController) Delete(c *gin.Context) {
	id := c.Param("id")
	prev, getErr := ctl.repo.Get(id)
	if err := ctl.repo.Delete(id); err != nil {
		if errors.Is(err, errNotFound) {
			apiNotFound(c, "acl")
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "delete failed"})
		return
	}
	if err := applyNftablesConfigFn(); err != nil {
		if getErr == nil {
			if rbErr := ctl.repo.Restore(prev); rbErr != nil {
				log.Printf("[WARN] restore of lan_acl %s after failed apply: %v", id, rbErr)
			}
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to apply nftables: " + err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

func (ctl *LanACLController) SetDefaultPolicy(c *gin.Context) {
	var req struct {
		Policy string `json:"policy"`
	}
	if err := c.BindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "bad request"})
		return
	}
	req.Policy = strings.ToLower(strings.TrimSpace(req.Policy))
	if req.Policy != "proxy" && req.Policy != "direct" {
		// The value is rendered into the nftables template.
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid policy (proxy|direct)"})
		return
	}
	previous := ctl.repo.GetDefaultPolicy()
	if err := ctl.repo.SetDefaultPolicy(req.Policy); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "db error"})
		return
	}
	if err := applyNftablesConfigFn(); err != nil {
		if rbErr := ctl.repo.SetDefaultPolicy(previous); rbErr != nil {
			log.Printf("[WARN] restore of lan default policy after failed apply: %v", rbErr)
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to apply nftables: " + err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}
