#!/bin/bash
# EdgeRouteGW Installation & Deployment Script
# Supports both fresh installs and updates.
# Usage: ./install.sh

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# NOTE:
# Xray/Mosdns 运行时配置由 backend 按模式动态生成并下发。
# - Mode A / Mode C: 禁用 FakeDNS/FakeIP
# - Mode B: 仅此模式启用 FakeDNS/FakeIP
# 请勿在部署脚本内写死模式相关业务配置，避免与运行态冲突。

echo "=== EdgeRouteGW Deployment Script ==="

# OS and Architecture Check
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "${ID:-}" != "debian" && "${ID:-}" != "ubuntu" ]]; then
        echo "Error: This script is only designed for Debian/Ubuntu based systems."
        exit 1
    fi
else
    echo "Warning: Cannot determine OS. Proceeding anyway..."
fi

ARCH=$(uname -m)
case "$ARCH" in
    x86_64) XRAY_ARCH="64"; MOSDNS_ARCH="amd64" ;;
    aarch64) XRAY_ARCH="arm64-v8a"; MOSDNS_ARCH="arm64" ;;
    *) echo "Error: Unsupported architecture: $ARCH"; exit 1 ;;
esac

REPO_DIR="/root/proxygw"

# Ensure repository exists for frontend and templates
if [ ! -d "$REPO_DIR/.git" ]; then
    echo "[0/6] Cloning EdgeRouteGW repository..."
    apt-get update >/dev/null 2>&1 || true
    apt-get install -y git >/dev/null 2>&1 || true
    git clone https://github.com/zlylong/EdgeRouteGW.git "$REPO_DIR"
fi

# Switch to repo dir before proceeding
cd "$REPO_DIR"
echo "[1/6] Installing system dependencies..."
apt-get update
# sqlite3: db_optimize.sh (run at the end of this script) and flush_cache.sh.
apt-get install -y nftables frr curl wget unzip iproute2 jq sqlite3
# The OSPF engine resolves every domain and geosite rule by shelling out to dig
# (ospf_dns_cache.go is the only resolution path since the Go resolver was
# dropped in 1.7.20). Without it Mode C publishes nothing at all and Mode B
# cannot resolve protected hosts. dnsutils is the pre-bookworm name.
apt-get install -y bind9-dnsutils || apt-get install -y dnsutils

echo "[2/6] Setting up routing rules and system settings..."

# Fail-safe DNS: Break systemd-resolved symlink and inject static public DNS
# This prevents the system from losing DNS resolution if installation fails or when port 53 is freed.
echo "Configuring fail-safe DNS..."
# Keep a copy of the original so uninstall.sh can put it back instead of
# guessing whether systemd-resolved is in use on this host.
if [ -e /etc/resolv.conf ] && [ ! -e /etc/resolv.conf.pre-proxygw ]; then
    cp -L /etc/resolv.conf /etc/resolv.conf.pre-proxygw 2>/dev/null || true
fi
chattr -i /etc/resolv.conf 2>/dev/null || true
rm -f /etc/resolv.conf
cat << 'RESOLV_EOF' > /etc/resolv.conf
nameserver 119.29.29.29
nameserver 223.5.5.5
nameserver 1.1.1.1
RESOLV_EOF

# Free port 53 from systemd-resolved
if [ -f /etc/systemd/resolved.conf ]; then
    # Anchored: a commented "#DNSStubListener=no" must not count as configured.
    if ! grep -q "^DNSStubListener=no" /etc/systemd/resolved.conf; then
        echo "Configuring systemd-resolved to free port 53..."
        sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
        sed -i 's/DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
        # Ensure it is set if not found
        if ! grep -q "^DNSStubListener=no" /etc/systemd/resolved.conf; then
            echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
        fi
        systemctl restart systemd-resolved || true
    fi
fi
# The backend adds its policy rules and routes by the table *name* "tproxy".
# Newer iproute2 (Debian 13) ships its defaults under /usr/share/iproute2 and
# may have no /etc/iproute2/rt_tables at all, so appending to that file failed
# and aborted the install; rt_tables.d/ is honoured by every supported release.
if ! grep -qsw "tproxy" /etc/iproute2/rt_tables /usr/share/iproute2/rt_tables /etc/iproute2/rt_tables.d/*.conf 2>/dev/null; then
    mkdir -p /etc/iproute2/rt_tables.d
    echo "100 tproxy" > /etc/iproute2/rt_tables.d/proxygw.conf
fi
# Add rule if not exists
ip rule show | grep -q "fwmark 0x1 lookup tproxy" || ip rule add fwmark 1 table tproxy 2>/dev/null || true
ip route show table tproxy | grep -q "local default dev lo" || ip route add local default dev lo table tproxy 2>/dev/null || true

# Apply system kernel tunings for Transparent Proxying
echo "Applying sysctl kernel tunings for BBR and TCP..."
# NOTE: no nf_conntrack.* keys here. The gateway datapath is TPROXY (the nft
# ruleset carries no `ct state` match), so nf_conntrack is never loaded on it
# and those keys do not exist in /proc when systemd-sysctl runs — they only
# produced "cannot stat ... No such file or directory" on every boot. NAT and
# its conntrack live on the remote nodes / main router, not here.
cat << 'SYSCTL_EOF' > /etc/sysctl.d/99-proxygw.conf
# /etc/sysctl.d/99-proxygw.conf
# Auto-generated by EdgeRouteGW Deployment

# --- 1. Routing & Forwarding ---
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.route_localnet = 1

# --- 2. TCP Ports & Concurrency ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 500000
net.core.somaxconn = 32768

# --- 3. Throughput & BBR ---
net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = bbr
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_fastopen = 3
SYSCTL_EOF
sysctl --system || true

# conf.default only seeds interfaces created after it is applied, and for
# send_redirects the kernel ORs conf.all with conf.<iface>, so every interface
# that already existed keeps the default of 1 and the gateway still emits ICMP
# redirects. A redirected client then talks to the main router directly and
# never enters the TPROXY chain, which silently defeats Mode A.
for _redir in /proc/sys/net/ipv4/conf/*/send_redirects; do
    [ -w "$_redir" ] && echo 0 > "$_redir" || true
done


echo "[3/6] Setting up directory structure..."
mkdir -p "$REPO_DIR/config"
mkdir -p "$REPO_DIR/core/mosdns"
mkdir -p "$REPO_DIR/core/xray"
mkdir -p "$REPO_DIR/core/nftables"
mkdir -p "$REPO_DIR/core/frr"
mkdir -p "$REPO_DIR/systemd"

echo "[4/6] Downloading backend from GitHub Releases..."
# Prefer the latest published release (the API excludes pre-releases). This
# script does not fetch an existing clone, so its local tags can be stale; they
# are only a fallback.
PROXYGW_LATEST=$(curl --retry 3 --connect-timeout 5 --fail -s -4 https://api.github.com/repos/zlylong/EdgeRouteGW/releases/latest | jq -r '.tag_name // empty' || true)

# Fallback: the newest stable tag reachable from the checkout. Stable only: a
# v1.9.0-rc.1 tag must not be picked over the released v1.8.x.
if [ -z "$PROXYGW_LATEST" ] && [ -d "$REPO_DIR/.git" ]; then
    PROXYGW_LATEST=$(cd "$REPO_DIR" && git describe --tags --abbrev=0 --exclude '*-*' 2>/dev/null || true)
fi

# Last resort: the newest stable tag in the clone. There is no hardcoded
# version any more; an install that cannot determine a release must stop
# rather than quietly pin an old one.
if [ -z "$PROXYGW_LATEST" ] && [ -d "$REPO_DIR/.git" ]; then
    PROXYGW_LATEST=$(cd "$REPO_DIR" && git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1 || true)
fi
if [ -z "$PROXYGW_LATEST" ]; then
    echo "Error: could not determine the release tag (git tags and GitHub API both unavailable)"; exit 1
fi

# verify_backend_checksum FILE ASSET_NAME TAG
# Releases publish SHA256SUMS next to the binaries. A mismatch is fatal: the
# file is a root-executed binary and a bad byte is worse than no update. A
# missing SHA256SUMS is fatal too (fail closed): a blocked or tampered
# download of the checksum list must not silently disable verification. Set
# PROXYGW_ALLOW_UNVERIFIED=1 to install a release that predates SHA256SUMS.
verify_backend_checksum() {
    local file="$1" asset="$2" tag="$3"
    local sums; sums=$(mktemp)
    if ! ${DOWNLOAD_CMD:-wget -q -4 -O} "$sums" "https://github.com/zlylong/EdgeRouteGW/releases/download/${tag}/SHA256SUMS" 2>/dev/null || [ ! -s "$sums" ]; then
        rm -f "$sums"
        if [ "${PROXYGW_ALLOW_UNVERIFIED:-0}" = "1" ]; then
            echo "Warning: no SHA256SUMS for ${tag}; PROXYGW_ALLOW_UNVERIFIED=1 set, skipping verification"
            return 0
        fi
        echo "Error: could not fetch SHA256SUMS for ${tag}; refusing to install an unverified binary"
        echo "       (set PROXYGW_ALLOW_UNVERIFIED=1 to override for releases that predate checksums)"
        rm -f "$file"; return 1
    fi
    local want; want=$(awk -v a="$asset" '$2==a {print $1}' "$sums")
    rm -f "$sums"
    if [ -z "$want" ]; then
        echo "Error: SHA256SUMS for ${tag} has no entry for ${asset}"; rm -f "$file"; return 1
    fi
    local got; got=$(sha256sum "$file" | awk '{print $1}')
    if [ "$want" != "$got" ]; then
        echo "Error: checksum mismatch for ${asset} (${tag})"
        echo "  expected ${want}"
        echo "  got      ${got}"
        rm -f "$file"; return 1
    fi
    echo "Checksum verified for ${asset} (${tag})"
}

if [ "$ARCH" = "x86_64" ]; then
    BACKEND_ASSET="proxygw-backend-linux-amd64"
elif [ "$ARCH" = "aarch64" ]; then
    BACKEND_ASSET="proxygw-backend-linux-arm64"
else
    echo "Error: unsupported architecture ${ARCH} (need x86_64 or aarch64)"; exit 1
fi
# Download next to the target and swap only after verification. Writing
# straight to proxygw-backend meant a failed or interrupted download on a
# re-run (this script doubles as an updater) left an empty file where the
# running install's binary used to be.
BACKEND_BIN="$REPO_DIR/backend/proxygw-backend"
BACKEND_NEW="$BACKEND_BIN.new"
if ! wget -q -4 -O "$BACKEND_NEW" "https://github.com/zlylong/EdgeRouteGW/releases/download/${PROXYGW_LATEST}/${BACKEND_ASSET}"; then
    rm -f "$BACKEND_NEW"
    echo "Error: failed to download ${BACKEND_ASSET} for ${PROXYGW_LATEST}"; exit 1
fi
verify_backend_checksum "$BACKEND_NEW" "$BACKEND_ASSET" "$PROXYGW_LATEST" || exit 1
chmod +x "$BACKEND_NEW"
mv -f "$BACKEND_NEW" "$BACKEND_BIN"


echo "[5/6] Creating Systemd services..."
cat << 'SYS_EOF' > /etc/systemd/system/proxygw.service
[Unit]
Description=EdgeRouteGW Backend Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/backend
ExecStart=/root/proxygw/backend/proxygw-backend
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

# Security Sandboxing
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
ReadWritePaths=-/root/proxygw -/usr/local/bin -/etc/frr -/etc/nftables.conf /proc/sys/net/ipv4/conf
# ProtectSystem=strict mounts /run read-only; the backend and the connection
# tracker write the Xray logs under /run/proxygw. Preserve keeps the directory
# (and Xray's open log file) across backend restarts.
RuntimeDirectory=proxygw
RuntimeDirectoryPreserve=yes

[Install]
WantedBy=multi-user.target
SYS_EOF

cat << 'SYS_EOF' > /etc/systemd/system/mosdns.service
[Unit]
Description=Mosdns Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/core/mosdns
ExecStart=/root/proxygw/core/mosdns/mosdns start -d /root/proxygw/core/mosdns
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
SYS_EOF

cat << 'SYS_EOF' > /etc/systemd/system/xray.service
[Unit]
Description=Xray Service
After=network.target network-online.target nss-lookup.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/proxygw/core/xray
Environment=XRAY_LOCATION_ASSET=/root/proxygw/core/xray
# The generated config logs under /run/proxygw, which proxygw.service creates
# (RuntimeDirectory=). At boot Xray may start first, and a missing log
# directory is one of the exit-23 cases RestartPreventExitStatus stops retrying.
ExecStartPre=/bin/mkdir -p /run/proxygw
ExecStart=/root/proxygw/core/xray/xray run -confdir /root/proxygw/core/xray
Restart=on-failure
# Xray exits 23 when it rejects its own configuration. Without this, a bad
# config turns Restart=on-failure into an endless restart loop that floods the
# journal instead of stopping with a diagnosable failure.
RestartPreventExitStatus=23
RestartSec=5
LimitNOFILE=1048576
LimitNPROC=10000

[Install]
WantedBy=multi-user.target
SYS_EOF


# ensure_core_binaries: (re)download Xray and Mosdns when the binaries under
# core/ cannot run on this host. The repository tracks amd64 builds of both, so
# on arm64 they have to be replaced after every clone and after every
# `git reset --hard` (update.sh), or mosdns/xray die with "exec format error".
# The check is "does `<bin> version` run", which is what matters for systemd.
# Downloads honour CORE_DOWNLOAD_CMD (FILE URL) and CORE_API_CMD (URL) so the
# caller can route them through a proxy.
ensure_core_binaries() {
    local tmp; tmp=$(mktemp -d)
    if ! "$REPO_DIR/core/xray/xray" version >/dev/null 2>&1; then
        echo "Downloading Xray for $ARCH..."
        local xray_url="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-${XRAY_ARCH}.zip"
        if ! ${CORE_DOWNLOAD_CMD:-wget -q -4 -O} "$tmp/xray.zip" "$xray_url"; then
            echo "Error: failed to download Xray (${xray_url})" >&2
            rm -rf "$tmp"; return 1
        fi
        # XTLS publishes a digest next to every asset; this binary runs as root.
        ${CORE_DOWNLOAD_CMD:-wget -q -4 -O} "$tmp/xray.zip.dgst" "${xray_url}.dgst" 2>/dev/null || true
        local want got
        want=$(awk '/^SHA2-256=/ {print $2}' "$tmp/xray.zip.dgst" 2>/dev/null || true)
        got=$(sha256sum "$tmp/xray.zip" | awk '{print $1}')
        if [ -z "$want" ]; then
            echo "Warning: could not fetch Xray digest; skipping verification"
        elif [ "$want" != "$got" ]; then
            echo "Error: Xray download failed verification (expected $want, got $got)" >&2
            rm -rf "$tmp"; return 1
        else
            echo "Xray download verified"
        fi
        unzip -qo "$tmp/xray.zip" xray -d "$REPO_DIR/core/xray/"
    fi
    chmod +x "$REPO_DIR/core/xray/xray" || true

    if ! "$REPO_DIR/core/mosdns/mosdns" version >/dev/null 2>&1; then
        echo "Downloading Mosdns for $ARCH..."
        local mosdns_latest
        mosdns_latest=$(${CORE_API_CMD:-curl --retry 3 --connect-timeout 5 --fail -s -4} https://api.github.com/repos/IrineSistiana/mosdns/releases/latest | jq -r '.tag_name // empty' || true)
        if [ -z "$mosdns_latest" ]; then
            echo "Error: could not determine the latest Mosdns release; the current core/mosdns/mosdns does not run on this host" >&2
            rm -rf "$tmp"; return 1
        fi
        if ! ${CORE_DOWNLOAD_CMD:-wget -q -4 -O} "$tmp/mosdns.zip" "https://github.com/IrineSistiana/mosdns/releases/download/${mosdns_latest}/mosdns-linux-${MOSDNS_ARCH}.zip"; then
            echo "Error: failed to download Mosdns ${mosdns_latest} for ${MOSDNS_ARCH}" >&2
            rm -rf "$tmp"; return 1
        fi
        unzip -qo "$tmp/mosdns.zip" mosdns -d "$REPO_DIR/core/mosdns/"
    fi
    chmod +x "$REPO_DIR/core/mosdns/mosdns" || true
    rm -rf "$tmp"

    local bin
    for bin in core/xray/xray core/mosdns/mosdns; do
        if ! "$REPO_DIR/$bin" version >/dev/null 2>&1; then
            echo "Error: $bin is not runnable on this host ($ARCH)" >&2
            return 1
        fi
    done
}

echo "[5.5/6] Verifying and Installing Core Binaries ($ARCH)..."
ensure_core_binaries || exit 1


echo "Applying strict anti-loop Nftables rules..."
# This ruleset is only a placeholder until the backend renders the real one
# (nftables_service.go) on its first start. Do not touch a ruleset that is not
# ours without keeping a copy.
if [ -f /etc/nftables.conf ] && [ ! -e /etc/nftables.conf.pre-proxygw ] && ! grep -q 'table inet proxygw' /etc/nftables.conf; then
    cp -p /etc/nftables.conf /etc/nftables.conf.pre-proxygw
fi
cat << 'NFT_EOF' > /etc/nftables.conf
#!/usr/sbin/nft -f
flush ruleset
table inet proxygw {
    chain prerouting {
        type filter hook prerouting priority mangle; policy accept;
        # Xray local output MUST bypass TProxy to prevent loop
        meta mark 0x02 return
        # Ignore LAN / Multicast / Broadcast traffic
        ip daddr { 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 224.0.0.0/4, 255.255.255.255/32 } return
        # Drop IPv6 traffic to prevent un-proxied leak when DNS resolves AAAA
        meta nfproto ipv6 drop
        # TProxy all remaining IPv4 traffic
        meta l4proto { tcp, udp } mark set 1 tproxy ip to 127.0.0.1:12345 accept
    }
    chain output {
        type route hook output priority mangle; policy accept;
        # Xray local output MUST bypass TProxy to prevent loop
        meta mark 0x02 return
        # Ignore LAN / Multicast / Broadcast traffic
        ip daddr { 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 224.0.0.0/4, 255.255.255.255/32 } return
        # Host egress stays direct, exactly as in the backend's template. Marking
        # it here sent the gateway's own DNS, apt and GitHub traffic to
        # 127.0.0.1:12345 before Xray had any config to listen with, which
        # blackholed the very downloads the backend needs on its first start.
        counter return comment "host_egress_direct"
    }
}
NFT_EOF
systemctl enable nftables
nft -f /etc/nftables.conf || true

echo "[6/6] Starting services..."
systemctl daemon-reload
systemctl enable proxygw mosdns xray || true

# Force restart if already running to pick up updates and generate bootstrap if needed
systemctl restart proxygw mosdns xray || true

# Run low-risk DB index optimization (idempotent, online-safe)
if [ -x "$REPO_DIR/scripts/db_optimize.sh" ] && [ -f "$REPO_DIR/config/proxygw.db" ]; then
    echo "Running DB index optimization (--index-only)..."
    "$REPO_DIR/scripts/db_optimize.sh" "$REPO_DIR/config/proxygw.db" --index-only || true
fi

# Automatically generate a secure password if it's a fresh install
# Wait for the database and bootstrap password to be initialized by the backend
echo "Waiting for EdgeRouteGW to initialize..."
for _ in {1..15}; do
    if [ -f "$REPO_DIR/config/bootstrap_password.txt" ]; then
        break
    fi
    sleep 1
done

if ! systemctl is-active --quiet proxygw; then
    echo "=========================================================="
    echo "Error: proxygw is not running after install. Inspect it with:"
    echo "  systemctl status proxygw --no-pager; journalctl -u proxygw -n 50 --no-pager"
    echo "=========================================================="
    exit 1
fi

if [ -f "$REPO_DIR/config/bootstrap_password.txt" ]; then
    echo "=========================================================="
    echo "EdgeRouteGW is running! A random initial password was generated:"
    cat "$REPO_DIR/config/bootstrap_password.txt"
    echo "Please login at http://$(hostname -I | awk '{print $1}') and CHANGE IT immediately."
    echo "=========================================================="
else
    echo "=========================================================="
    echo "EdgeRouteGW is running at http://$(hostname -I | awk '{print $1}')"
    echo "If this is a fresh install, check the backend logs for the bootstrap password."
    echo "=========================================================="
fi
